name: calendar
description: Hijri Calendar.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
# --build-name:
# --build-number:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  # syncfusion_flutter_calendar: ^19.2.60
  syncfusion_flutter_datepicker: ^19.2.60
  # hawk_fab_menu: ^0.3.2
  provider: ^5.0.0
  get: ^4.3.4
  shared_preferences: 
  # flutter_native_splash: ^1.1.7
  url_launcher: ^6.0.4
  flutter_launcher_icons: 
  
  # flutter_staggered_grid_view: ^0.4.0
  # table_calendar: ^3.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
